language: cpp

compiler:
    - clang++-3.5

before_install:
    - wget -O llvm.key http://llvm.org/apt/llvm-snapshot.gpg.key && sudo apt-key add llvm.key
    - sudo add-apt-repository -y 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.5 main'
    - sudo apt-get update

install:
    - sudo apt-get install clang-3.5 && export CXX=clang++-3.5

before_script:
    - mkdir build
    - cd build
    - mkdir TemplatiousLib
    - pushd TemplatiousLib
    - git clone https://github.com/davidkazlauskas/templatious.git
    - popd
    - cmake ..

script:
    - make && ./a.out

env:
    - TEMPLATIOUS_DIR=$TRAVIS_BUILD_DIR/build/TemplatiousLib

os:
    - linux

